### ISSUE TITLE
Handle bad data from Atlassian

### ISSUE THREAD

**Issue by boris-moduscreate** [Atlas-Authority/marketing-automation#158]
Anytime there is something that is required for us to parse to create a deal, make sure we log it and proceed further. For example:

```
TypeError: Cannot read properties of undefined (reading 'email')
    at getContactInfo (/usr/src/app/src/lib/marketplace/raw.ts:111:24)
    at Function.fromRaw (/usr/src/app/src/lib/model/license.ts:108:39)
    at /usr/src/app/src/lib/marketplace/marketplace.ts:41:56
    at Array.map (<anonymous>)
    at Marketplace.importData (/usr/src/app/src/lib/marketplace/marketplace.ts:41:37)
    at new DataSet (/usr/src/app/src/lib/data/set.ts:39:15)
    at DataManager.dataSetFrom (/usr/src/app/src/lib/data/manager.ts:52:21)
    at work (/usr/src/app/src/bin/main.ts:30:33)
    at Timeout.run [as _onTimeout] (/usr/src/app/src/lib/util/runner.ts:24:7)
```

**Comment by boris-moduscreate** [comment]
Looks like this can also happen with other fields like Maintenance end date:

```
Error: Missing field (in ALI-43409962): license.data.maintenanceEndDate (found undefined)
    at validateField (/usr/src/app/src/lib/marketplace/validation.ts:113:30)
    at assertRequiredLicenseFields (/usr/src/app/src/lib/marketplace/validation.ts:82:3)
    at Array.forEach (<anonymous>)
    at Marketplace.importData (/usr/src/app/src/lib/marketplace/marketplace.ts:47:14)
    at new DataSet (/usr/src/app/src/lib/data/set.ts:39:15)
    at DataManager.dataSetFrom (/usr/src/app/src/lib/data/manager.ts:52:21)
    at work (/usr/src/app/src/bin/main.ts:30:33)
    at Timeout.run [as _onTimeout] (/usr/src/app/src/lib/util/runner.ts:24:7)
```
