### ISSUE TITLE
Proceed on error in hubspot 

### ISSUE THREAD

**Issue by boris-moduscreate** [Atlas-Authority/marketing-automation#174]
Had a run fail with because the user typo'd the TLD in the email address. I sanitized it in the below log sample:

2023-09-04T08:56:41.532753458Z 9/4/2023, 8:56:41 AM ERR! Runner Error:
2023-09-04T08:56:41.547292885Z 9/4/2023, 8:56:41 AM ERR! Runner   Error: Property values were not valid: [{"isValid":false,"message":"Email address name@domain.<INVALID TLD> is invalid","error":"INVALID_EMAIL","name":"email"}]
2023-09-04T08:56:41.547310645Z 9/4/2023, 8:56:41 AM ERR! Runner       at /usr/src/app/src/lib/hubspot/api.ts:106:15
2023-09-04T08:56:41.547315007Z 9/4/2023, 8:56:41 AM ERR! Runner       at async Promise.all (index 50)
2023-09-04T08:56:41.547317974Z 9/4/2023, 8:56:41 AM ERR! Runner       at HubspotAPI.batchUpsert (/usr/src/app/src/lib/hubspot/api.ts:110:26)
2023-09-04T08:56:41.547321015Z 9/4/2023, 8:56:41 AM ERR! Runner       at HubspotAPI.createEntities (/usr/src/app/src/lib/hubspot/api.ts:71:12)
2023-09-04T08:56:41.547323795Z 9/4/2023, 8:56:41 AM ERR! Runner       at HubspotUploader.syncUpAllEntitiesProperties (/usr/src/app/src/lib/hubspot/uploader.ts:35:23)
2023-09-04T08:56:41.547326957Z 9/4/2023, 8:56:41 AM ERR! Runner       at HubspotUploader.upsyncChangesToHubspot (/usr/src/app/src/lib/hubspot/uploader.ts:19:5)
2023-09-04T08:56:41.547343221Z 9/4/2023, 8:56:41 AM ERR! Runner       at work (/usr/src/app/src/bin/main.ts:38:5)
2023-09-04T08:56:41.547346251Z 9/4/2023, 8:56:41 AM ERR! Runner       at run (/usr/src/app/src/lib/util/runner.ts:24:7)
2023-09-04T08:56:41.547348808Z 9/4/2023, 8:56:41 AM WARN Runner Run canceled by error. Trying again in 10m.

Can we create a general solution for proceeding when a given entity fails to upsert into hubspot?

Logged this with Atlassian at https://ecosystem.atlassian.net/servicedesk/customer/portal/34/ECOHELP-25511

**Comment by boris-moduscreate** [comment]
@khanguyen88 After merging in the above I am now seeing a failure with:

```
2023-09-14T13:27:38.029910969Z 9/14/2023, 1:27:38 PM ERR! Runner Error:
2023-09-14T13:27:38.044864420Z 9/14/2023, 1:27:38 PM ERR! Runner   Error: Trying to access null deal id!
2023-09-14T13:27:38.044887204Z 9/14/2023, 1:27:38 PM ERR! Runner       at Contact.guaranteedId (/usr/src/app/src/lib/hubspot/entity.ts:58:25)
2023-09-14T13:27:38.044907030Z 9/14/2023, 1:27:38 PM ERR! Runner       at /usr/src/app/src/lib/hubspot/uploader.ts:97:30
2023-09-14T13:27:38.044911601Z 9/14/2023, 1:27:38 PM ERR! Runner       at Array.map (<anonymous>)
2023-09-14T13:27:38.044915750Z 9/14/2023, 1:27:38 PM ERR! Runner       at HubspotUploader.syncUpAllAssociations (/usr/src/app/src/lib/hubspot/uploader.ts:93:10)
2023-09-14T13:27:38.044920294Z 9/14/2023, 1:27:38 PM ERR! Runner       at HubspotUploader.upsyncChangesToHubspot (/usr/src/app/src/lib/hubspot/uploader.ts:22:5)
2023-09-14T13:27:38.044924190Z 9/14/2023, 1:27:38 PM ERR! Runner       at work (/usr/src/app/src/bin/main.ts:38:5)
2023-09-14T13:27:38.044928243Z 9/14/2023, 1:27:38 PM ERR! Runner       at run (/usr/src/app/src/lib/util/runner.ts:24:7)
```

**Comment by boris-moduscreate** [comment]
Failing with

```
2023-09-15T14:47:47.446620363Z 9/15/2023, 2:47:47 PM ERR! Runner   TypeError: Converting circular structure to JSON
2023-09-15T14:47:47.446651599Z 9/15/2023, 2:47:47 PM ERR! Runner       --> starting at object with constructor 'DealManager'
2023-09-15T14:47:47.446655506Z 9/15/2023, 2:47:47 PM ERR! Runner       |     property 'entities' -> object with constructor 'Array'
2023-09-15T14:47:47.446658735Z 9/15/2023, 2:47:47 PM ERR! Runner       |     index 0 -> object with constructor 'Deal'
2023-09-15T14:47:47.446661567Z 9/15/2023, 2:47:47 PM ERR! Runner       --- property 'indexer' closes the circle
2023-09-15T14:47:47.446664299Z 9/15/2023, 2:47:47 PM ERR! Runner       at JSON.stringify (<anonymous>)
2023-09-15T14:47:47.446667179Z 9/15/2023, 2:47:47 PM ERR! Runner       at /usr/src/app/src/lib/hubspot/uploader.ts:95:113
2023-09-15T14:47:47.446670148Z 9/15/2023, 2:47:47 PM ERR! Runner       at Array.filter (<anonymous>)
2023-09-15T14:47:47.446672897Z 9/15/2023, 2:47:47 PM ERR! Runner       at HubspotUploader.syncUpAllAssociations (/usr/src/app/src/lib/hubspot/uploader.ts:93:10)
2023-09-15T14:47:47.446675979Z 9/15/2023, 2:47:47 PM ERR! Runner       at HubspotUploader.upsyncChangesToHubspot (/usr/src/app/src/lib/hubspot/uploader.ts:22:5)
2023-09-15T14:47:47.446678918Z 9/15/2023, 2:47:47 PM ERR! Runner       at work (/usr/src/app/src/bin/main.ts:38:5)
2023-09-15T14:47:47.446681917Z 9/15/2023, 2:47:47 PM ERR! Runner       at Timeout.run [as _onTimeout] (/usr/src/app/src/lib/util/runner.ts:24:7)
```

**Comment by boris-moduscreate** [comment]
Looks good.

**Comment by boris-moduscreate** [comment]
@khanguyen88 I am getting the original error from this issue again. Did we actually handle the scenario of us trying to perform the batch upsert into HubSpot and it getting rejected?

**Comment by khanguyen88** [comment]
@boris-moduscreate do you have the new stacktrace? 

I guess Hubspot might've changed something on their API, and the API client we're using is too outdated to work properly

**Comment by boris-moduscreate** [comment]
@khanguyen88 sent via Slack as it has PII and I didn't want to manually scrub it.
