### ISSUE TITLE
Error: Primary duplicate is accounted for twice: XXXXXXXXXXXX

### ISSUE THREAD

**Issue by apwidejulien** [Atlas-Authority/marketing-automation#184]
It seems a new "pattern" appeared recently in our marketplace reporting; several entries with same order id (transaction id):
![image](https://github.com/Atlas-Authority/marketing-automation/assets/51111685/ffc55e55-0820-43d4-b763-e0e54d0df9ee)

For the provided example, we have:
* 1 for refund a previous transaction.
* 1 for upgrade + change billing period monthly to annual maintenance period on 2024
* 1 for renewal on annual maintenance period 2025.

This result raise an error in action generation:
`
Get action for event upgrade , Transaction ID: (AT)IN-EU-000-656-718[AEI-04a806ba-3b02-349e-a8c4-6d6cdc1c93c1]
Found duplicate deals. Pick single deal:  20358085480 , deals to delete: [ '20358085481' ]
Get action for event renewal , Transaction ID: (AT)IN-EU-000-656-718[AEI-04a806ba-3b02-349e-a8c4-6d6cdc1c93c1]
Found duplicate deals. Pick single deal:  20358085480 , deals to delete: [ '20358085481' ]
7/3/2024, 6:14:35 AM ERR! Runner Error:
7/3/2024, 6:14:35 AM ERR! Runner   Error: Primary duplicate is accounted for twice: 20358085480
7/3/2024, 6:14:35 AM ERR! Runner       at ActionGenerator.singleDeal (/usr/src/app/src/lib/deal-generator/actions.ts:210:15)
7/3/2024, 6:14:35 AM ERR! Runner       at ActionGenerator.actionForRenewal (/usr/src/app/src/lib/deal-generator/actions.ts:105:23)
7/3/2024, 6:14:35 AM ERR! Runner       at ActionGenerator.actionsFor (/usr/src/app/src/lib/deal-generator/actions.ts:46:36)
7/3/2024, 6:14:35 AM ERR! Runner       at /usr/src/app/src/lib/deal-generator/actions.ts:39:41
7/3/2024, 6:14:35 AM ERR! Runner       at Array.flatMap (<anonymous>)
7/3/2024, 6:14:35 AM ERR! Runner       at ActionGenerator.generateFrom (/usr/src/app/src/lib/deal-generator/actions.ts:39:19)
7/3/2024, 6:14:35 AM ERR! Runner       at DealGenerator.generateActionsForMatchedGroup (/usr/src/app/src/lib/deal-generator/deal-generator.ts:103:42)
7/3/2024, 6:14:35 AM ERR! Runner       at /usr/src/app/src/lib/deal-generator/deal-generator.ts:46:51
7/3/2024, 6:14:35 AM ERR! Runner       at withAutoClose (/usr/src/app/src/lib/util/helpers.ts:28:12)
7/3/2024, 6:14:35 AM ERR! Runner       at DealGenerator.run (/usr/src/app/src/lib/deal-generator/deal-generator.ts:42:25)
`

I would be more than happy to help with, but not sure how to deal with this:
* should it be handled the same way than refund during event generation and merging several entries for same order id with renewal/upgrade type on one event + sum the amount ?
* should it be handled on action generation to avoid duplicated error when processing several event with same transaction id, but how: updating an existing deal with the second transaction, or creating a new deal ?

Thanks in advance for your help!

**Comment by nhan-nguyen-se** [comment]
The questions are about business logic which I have very little with this app. @apwidejulien Do we have a deduplication logic already? If so I think we can extend it to handle more duplication cases we found here.

**Comment by boris-moduscreate** [comment]
Hmm ok I think that makes sense @apwidejulien Any chance you can help with the core changes?

**Comment by apwidejulien** [comment]
Hi @boris-moduscreate ,

I've tried to integrate transactionLineItemId in the core engine: https://github.com/apwide/marketing-automation/commit/e86f9aed5280e735d829c028bf5d3e31ae5892a5

What is in my proposal:
- added new required hubspot attribute for transactionLineItemId (mapping and doc in readme)
- use pair txId/transactionLineItemId to identify and map deal <=> mpac transactions.
- search deals first by pair txId/txLineItemId and if nothing found, fallback on old strategy, search only by txId. (tries to migrate on the fly old record and update them with line id)
- added unit test based on deal state (existing vs new).

This last assumption makes that we face same original issue with duplicate Error in case some records exists in HubSpot with transactionId only and engine tries to process several transactionLine in MAPC for the same transactionId.
I don't know exactly how to proceed with this case because there is no "data conversion" for what it is in Hubspot... We should probably find a way to migrate this...

Let me know what you think about it.

**Comment by boris-moduscreate** [comment]
@nhan-nguyen-se Can you take a look at the changes Julien has shared?

**Comment by nhan-nguyen-se** [comment]
It looks fine to me.

**Comment by boris-moduscreate** [comment]
@apwidejulien I wanted to check back on my last comment here.

**Comment by apwidejulien** [comment]
@boris-moduscreate ,

Sorry, I was off.

For legacy items, in case we find several deals for purchase/renewal (actionForRenewal/actionForPurchase) for a given txId without txLineId, we could try to distinguish them based on the amount. And if amount is not enough to match a transaction to a deal, we could ignore them as you proposed ?

Do you have any example of such ignore stuff ? I don't see any similar approach in the code for now.

**Comment by boris-moduscreate** [comment]
Hope you had a great time off @apwidejulien!

I don't think the engine should stop is my point. This would be a bunch of manual work for anyone and would block initial deployment. Instead we log to slack, allow the user to clean stuff up like you said, but continue the run. And then have an env variable like "DELETE_BLOCKING_DEALS=YES" to have it auto delete.

We likely want the same functionality for errors like:

```
Error: Primary duplicate is accounted for twice: 21214688382
    at ActionGenerator.singleDeal (/usr/src/app/src/lib/deal-generator/actions.ts:210:15)
    at ActionGenerator.actionForRenewal (/usr/src/app/src/lib/deal-generator/actions.ts:105:23)
    at ActionGenerator.actionsFor (/usr/src/app/src/lib/deal-generator/actions.ts:46:36)
    at /usr/src/app/src/lib/deal-generator/actions.ts:39:41
    at Array.flatMap (<anonymous>)
    at ActionGenerator.generateFrom (/usr/src/app/src/lib/deal-generator/actions.ts:39:19)
    at DealGenerator.generateActionsForMatchedGroup (/usr/src/app/src/lib/deal-generator/deal-generator.ts:103:42)
    at /usr/src/app/src/lib/deal-generator/deal-generator.ts:46:51
    at withAutoClose (/usr/src/app/src/lib/util/helpers.ts:28:12)
    at DealGenerator.run (/usr/src/app/src/lib/deal-generator/deal-generator.ts:42:25)
    ```

**Comment by apwidejulien** [comment]
Thanks @boris-moduscreate, yes, may days off were relaxing! ;)

I've created this https://github.com/Atlas-Authority/marketing-automation/pull/185 to added changes you requested + small additions:

Changes requested:

- log and register blocking deals
- when blocking deal found, stop deal generation only for affected "related licenses set" and remove deal from dataset for not updating it
- print blocking deals in deal generation summary
- added option to automatically delete deal and their duplicates

For the auto delete, we have to delete all of the deals related to a txId because they are all representing the same txId without txLineId.
When this option is enabled, we have this flow:

- Execution 1: blocking deals are detected and deleted, including all of their duplicates.
- Execution 2: deals are re-created with their corresponding transactionLineItemId field, so, no more duplication.

I've also added additional commits (which I can remove or push on different PRs if you prefer):

- added some files to .gitgnore, I hope it's not a big deal for you (.npmrc/.yarnrc)
- added a docker compose file to be able to run it locally more easily
- moved the license filtering by email before the validation of mpac mandatory field. (it's quite convenient to ignore by email when marketplace api returns some invalid data which blocks the engine, such as tier field which currently is missing on some of our records)

I've ran it on our instance with auto delete enabled and after having configured the mandatory transactionLineItemId field. Execution has:

- Updated existing valid deals (deal with only a transactionId but having no multi line/txId in mapc) with their transactionLineItemId.
- Deleted the problematic deals on first execution.
- Re-created previous problematic deals with their transactionLineItemId.

I let you review my code and let me know what you think of it.
